import React, { useEffect, useState } from 'react';
import Head from "next/head";
import Image from "next/image";
import { navBarRoutes, navBarBottomBars, medias  } from './Constants'
import { footerImage } from '../Footer/Constants'
import s from './Navbar.module.css'

const Navbar = () => {

  const [currentRoute, setCurrentRoute] = useState(null)
  const whiteListRoutes = [0,1,2,5,8]

  const onHoverRouteCell = (index) => {
    if(currentRoute !== null){
      const previousBottomRow = document.getElementById(`bottomRow${currentRoute}`)
      previousBottomRow.style.top = `0px`;
      previousBottomRow.style.opacity = 0;  
    }
    if(whiteListRoutes.includes(index)){
      setCurrentRoute(index)
      const bottomRow = document.getElementById(`bottomRow${index}`)
      bottomRow.style.top = `${70}px`;
      bottomRow.style.opacity = 1;
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.navBarOffset}/>
      <div className={s.navBarContainer}>
        <div className={s.navBarTopRowContainer}>
          <div className={s.imageContainer}>
            <Image 
              src={footerImage}
              width={96}
              height={96}
              className={s.icon}
              alt={'footerImg'}
            />
          </div>
          <div className={s.routesContainer}>
            {navBarRoutes.map((item, index) => 
              <div 
                key={`${item} ${index}`}
                className={s.routeCell}
                onMouseEnter={(e) => onHoverRouteCell(index)}
                // onMouseLeave={() => onLeaveRouteCell(index)}
              >
                {item}
              </div>  
            )}
          </div>
          <div className={s.languageContainer}>
          </div>
        </div>
      </div>
      {
        navBarBottomBars.map((routes, index) => (
          <div key={`navBarRoutes ${index}`} className={s.navBarBottomRowContainer} id={`bottomRow${index}`}>
            {
              index === 3 
              ? 
                (
                  null
                )
              : 
                (
                  routes.map((item, subIndex) => (
                    <div key={`${item} ${subIndex}`} className={s.bottomRowRoutes}>
                      {item}
                    </div>
                  ))
                )
            }
          </div>
        ))
      }
      <div className={s.rightBottomFixedMediasContainer}>
        {medias.map((item, index) =>
          <a key={`${item.url} ${index}`} href={item.url} target={'_blank'}>
            <Image
              src={item.icon}
              className={s.mediaIcon}
              alt={'mediaIcons'}
            />  
          </a> 
        )}
      </div>
    </>
  )
}

export default Navbar