import React from 'react';
import Head from "next/head";
import Image from "next/image";
import { navBarRoutes } from './Constants'
import s from './Navbar.module.css'


const Navbar = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.navBarOffset}/>
      <div className={s.navBarContainer}>
        <div className={s.navBarTopRowContainer}>
          <div className={s.imageContainer}>
            <Image 
              src={'/footerImg.png'}
              width={96}
              height={96}
              className={s.icon}
            />
          </div>
          <div className={s.routesContainer}>
            {navBarRoutes.map(item => 
              <div className={s.routeCell}>
                {item}
              </div>  
            )}
          </div>
          <div className={s.languageContainer}>
          </div>
        </div>
        <div className={s.navBarBottomRowContainer}>

        </div>
        <div className={s.rightBottomFixedMediasContainer}>

        </div>
      </div>
    </>
  )
}

export default Navbar